### ISSUE TITLE
Size monitor maybe broken

### ISSUE THREAD

**Issue by alexanderkershaw** [alexanderkershaw/wow-recorder#8]
The size monitor should clean up old videos after the limit is exceeded. 

Instead it hits the below error: 

```
stdout: Namespace(storage='D:\\wow-recorder-files', logs='D:\\World of Warcraft\\_retail_\\Logs', size=80, ffmpeg='C:\\Users\\alexa\\AppData\\Local\\Programs\\WarcraftRecorder\\resources\\ffmpeg\\ffmpeg.exe')
Size monitor results: Used:82, Limit:80
Deleting oldest video
stderr: Traceback (most recent call last):
  File "main.py", line 36, in <module>
  File "SizeMonitor.py", line 26, in run
  File "SizeMonitor.py", line 50, in delete_oldest_video
ValueError: min() arg is an empty sequence
[1904] Failed to execute script 'main' due to unhandled exception!
```

**Comment by alexanderkershaw** [comment]
Resolved in 1.0.2
